/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Q2Ex07;

import characters.NPC;
import characters.Trainer;
import locations.Location;
import monsters.FireType;

public class App {
    public static void main(String[] args) {
        Trainer person = new Trainer("Ash");

        FireType monster = new FireType("Charmander", 146, 99);
        person.inspect(monster);

        NPC mom = new NPC("Mom", "Hello there! Do you want to rest?");
        person.inspect(mom);

        Location house = new Location("Home", "mom's cooking");
        person.inspect(house);
    }
}
