/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Q2Ex07;

import monsters.FireType;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        FireType monster = new FireType("Charmander", 100, 100);
        monster.special();
    }
}
