/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Q2Ex09;

import java.util.Scanner;

public class App {
    public static void main(String[] args){
        Scanner sc = new Scanner(System.in);
        
        int notfound = 0;
        int alreadycaptured = 0;
        int fullteam = 0;
        int notinteam = 0;
        
        Trainer player = new Trainer("Steve");
        Monster m0 = new Monster("Rattata", "Normal", "None", "None", 15, 5);
        Monster m1 = new Monster("Meowth", "Normal", "None", "None", 15, 5);
        Monster m2 = new Monster("Kangaskhan", "Normal", "None", "None", 15, 5);
        Monster m3 = new Monster("Tauros", "Normal", "None", "None", 15, 5);
        Monster m4 = new Monster("Ditto", "Normal", "None", "None", 15, 5);
        Monster m5 = new Monster("Eevee", "Normal", "None", "None", 15, 5);
        Monster m6 = new Monster("Porygon", "Normal", "None", "None", 15, 5);
        Monster m7 = new Monster("Snorlax", "Normal", "None", "None", 15, 5);
        Monster m8 = new Monster("Sentret", "Normal", "None", "None", 15, 5);
        Monster m9 = new Monster("Dunsparce", "Normal", "None", "None", 15, 5);
        
        String input = "";
        
        while(!input.equals("exit")){
            try {
                System.out.print("What will the trainer do? ");
            input = sc.nextLine();
            Monster selected = null;
            if(input.equals("catch") || input.equals("release")){
                System.out.print("Which monster? ");
                String name = sc.nextLine();
                selected = Monster.selectMonster(name);
            }
            
            switch(input){
                case "catch":
                    player.sureCapture(selected);
                    break;
                case "release":
                    player.release(selected);
                    break;
                case "exit":
                    break;
                default:
                    System.out.println("Invalid input.");
            }
            } catch (MonsterNotFoundException e) {
                notfound += 1;
                System.out.println("Monster not found. Please try again.");
                continue;
            } catch (FullTeamException e) {
                fullteam += 1;
                System.out.println("Your team is full. Please try again.");
                continue;
            } catch (NotInTeamException e) {
                notinteam += 1;
                System.out.println("You can't release a monster you don't have. Please try again.");
                continue;
            } catch (AlreadyCapturedException e) {
                alreadycaptured += 1;
                System.out.println("You can't have two of the same monster on a team. Please try again.");
                continue;
            } catch (Exception e) {
                System.out.println("An unknown error occured. Please try again.");
                continue;
            }
        }
        
        System.out.printf("Encountered errors:%n"
                + "MonsterNotFoundException: %d%n"
                + "AlreadyCapturedException: %d%n"
                + "FullTeamException: %d%n"
                + "NotInTeamException: %d%n", 
                notfound, alreadycaptured, fullteam, notinteam);
        
        sc.close();
    }
    
}